# -*- coding: utf-8 -*-
"""
Created on Tue Oct  1 11:05:43 2024

@author: gerdy
"""

"""
This is the second version of the Fluorescence2Mask script. Different util functions will be 
contained in different scripts.
"""
#______________________________Add parent directory to import paths___________
import os
import sys

rootpath = os.path.join(os.getcwd(), '..')
sys.path.append(rootpath)

import pickle
import time
from datetime import datetime

#_______________________________ Library Imports______________________________
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

import pyclesperanto_prototype as cle

import _HelperFunctions as hf

import _parameter
import importlib
#_____________________________ Function definitions___________________________
importlib.reload(_parameter)
from _parameter import p



def ellipse_fit(img, Indices: list[tuple], box_half = 17, size_interval = (10,30), scale_factor = 0.9):
    """ 
    Draws a mask of ellipses generated by fitting shapes in img to ellipses.
    
    img, Indices: This function goes through all indices given in Indices and performs an ellipse fit.
    
    box_half: It isolates a box of side length 2 * box_half. 
    size_interval: Every ellipse too big or too small is discarded and not drawn.
    scale_factor: It has been seen that ellipses are fit in size excess
    """
    
    img_t = img.copy() 

    # Loop through the possible neurons detected and fit an ellipse around each one.
    lower_limit, upper_limit = size_interval

    count = 0
    mask = np.zeros(img.shape)
    
    for index in Indices:                                     
        i,j = index[0], index[1]  
        
        crop_img = img_t[i-box_half : i+box_half, j-box_half : j+box_half]
        
        cnts, hiers = cv.findContours(crop_img, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)[-2:]
        
        for cnt in cnts:
            try:            
                scale_factor_t = scale_factor
                
                # Fits the ellipse around the isolated location.
                ellipse = cv.fitEllipse(cnt)   
                
                #  Ellipse sizes checks.
                if lower_limit > ellipse[1][0] or lower_limit > ellipse[1][1]:      
                    # Too small.
                    continue
                
                elif ellipse[1][0] < upper_limit and ellipse[1][1] < upper_limit:            
                    # Right size.
                    new_ellipse = ((ellipse[0][0]+j-box_half, ellipse[0][1]+i-box_half),(ellipse[1][0] * scale_factor_t, ellipse[1][1] * scale_factor_t), ellipse[2])
                    cv.ellipse(mask, new_ellipse, (255,0, 0), -1, cv.LINE_AA)
                    
                    count+=1
                    
                elif (ellipse[1][0] > upper_limit or ellipse[1][1] > upper_limit) and abs(ellipse[1][0]-ellipse[1][1]) < p["eccentricity4_3"]:
                    # Too big in a specific axes.
                    if abs(ellipse[1][0]-ellipse[1][1]) > 100:
                        scale_factor_t = scale_factor_t / 2
                    
                    if ellipse[1][0] < ellipse[1][1]:
                        new_ellipse = ((int(j), int(i)),(ellipse[1][0] * scale_factor_t, ellipse[1][0]), ellipse[2])
                        
                    else:
                        new_ellipse = ((int(j), int(i)),(ellipse[1][1], ellipse[1][1] * scale_factor_t), ellipse[2])
                    
                    # if new_ellipse[1][0] > 1.5 * upper_limit or ellipse[1][1] > 1.5 * upper_limit: continue   # NEW LINE ADDED
                    
                    cv.ellipse(mask, new_ellipse, (255, 0, 0), -1, cv.LINE_AA)

                    count+=1
            
            except Exception as e:
                
                if e.code != -201:
                    print(f"Unexpected Error {e.code}.\n{e.err}")
                continue
        
    return mask.astype("uint8")
    

def erase_border_neurons(mask):
    """
    Detects the neurons that don't appar whole in the mask and erases them. It first detects the 
    border of the mask and then flags them to be erased if there are more than 9 pixels in a row.
    """
    shape = mask.shape
    borders = mask.copy()
    
    # Sets up the indices that will help the algorithm check the borders
    ENUM = [["TOP", (1, 1)], ["BOTTOM", (1, -1)],
            ["LEFT", (0, 1)], ["RIGHT", (0, -1)]]
    BORDER = {}

    # This loop finds the column or row that first has a non-zero pixel.
    for side in ENUM:
        orientation, index = side[1]
        scan = np.zeros(shape)
        if orientation == 1:
            for a in range(0, shape[0]):
                
                i = index * a
                
                scan[i, :] = 1
                borders = mask.astype(int) & scan.astype(int)
                
                if np.sum(borders) > 0.9:
                   BORDER[side[0]] = (a, borders[i, :]) 
                   break
                
        else: 
            for a in range(0, shape[1]):
                i = index * a
                
                scan[:, i] = 1
                borders = mask.astype(int) & scan.astype(int)
                
                if np.sum(borders) > 0.9:
                   BORDER[side[0]] = (a, borders[:, i]) 
                   break

    # dict BORDER is "Side": (border_depth, extracted_border_column)
    Flagged_neuron = {"TOP": [], "BOTTOM": [], "LEFT": [], "RIGHT": []}
    
    # This loop flags neurons in the borders that have more than 10 consecutive pixels.
    for side in BORDER:
        array = BORDER[side][1]
        consecutive_pixels = 0
        for n, i in enumerate(array):
            if i == 0: 
                consecutive_pixels = 0
                
            else:
                consecutive_pixels += 1
                
                """
                Note: The number 10 is chosen based on the output of the 
                function in this same script "DrawCircle_of_Area"
                """
                if consecutive_pixels >= 10:
                    Flagged_neuron[side].append((BORDER[side][0], n))
                    consecutive_pixels = 0
    

    # Transform to absolute coordinates
    Flagged_neuron_coord = {"TOP": [], "BOTTOM": [], "LEFT": [], "RIGHT": []}
    for side in ENUM:
        for neuron in Flagged_neuron[side[0]]:
            coord1 = (neuron[0] * side[1][1], neuron[1])
            if side[1][0] == 0:
                coord2 = (coord1[1], coord1[0])
            else:
                coord2 = coord1
            Flagged_neuron_coord[side[0]].append(coord2)

    # This has the coordinates of the neurons to be erased.
    img_treated = mask.copy()
    for side in ENUM:
        for neuron in Flagged_neuron_coord[side[0]]:
            img_treated = hf.size_filter_v2(img_treated, coord = neuron, n_area_m=(0, 0))
    
    return img_treated


def F2EMask(original_img, *, tolerance = 0, box_half = 17, size_interval = (10,30), sigma = 3.):
    """
    Generates a binary mask based on detecting maxima and fitting ellipses around each maxima. 
    
    Arguments:
        - tolerance: When calculating the mean pixel value --> img[img < (mean_pixel + tolerance)] = 0
        - size interval: The minimum and maximum axes sizes when drawing ellipses
        - sigma: Factor controlling the blur in the first stage, where neuron locations are detected.
        
    Returns:
        - Count of the number of ellipses drawn -> Interpreted as the number of neurons in the image.
        - Eroded Mask.
    """

    img = original_img.copy()

    mean_pixel = img.mean()
    img[img < (mean_pixel + tolerance)] = 0

    img_relevant_maxima, number_of_relevant_maxima_locations = hf.detect_maxima(img, sigma = sigma)

    # If there are no neurons left after threshold
    if number_of_relevant_maxima_locations == 0:
        return None, None
        
    # Extract the neuron locations
    Indices = hf.extract_non_zero(img_relevant_maxima)
    
    imgB= np.array(cle.threshold_otsu(img)) 
    imgB[imgB > 0] = int(1)
    
    # Fits all the ellipses, img_fill_holes is a binary mask.
    img_fill_holes = ellipse_fit(img, Indices, box_half = box_half, size_interval = size_interval)

    # Erode the ellipses (binary AND mask) based on the image to get a  fitting shape
    img_fill_holes[img_fill_holes < 10] = int(0); img_fill_holes[img_fill_holes > 10] = int(1)
    img_eroded = np.bitwise_and(img_fill_holes, imgB)

    # This is the extra in version 5.1. Inflates the neurons enough to also include the edges.
    Kernel = np.ones((3,3), dtype="uint8")
    img_eroded = cv.dilate(img_eroded, Kernel, iterations=1)

    return img_relevant_maxima, img_eroded   

    
def E2SMask(img_eroded, img_relevant_maxima):
    """
    Separates the neurons based on the relevant maxima locations detected in the flourescence,
    which are much more precise than detecting them on the mask.
    """
    img = img_eroded.copy()

    # Voronoi neuron separation
    voronoi_separation = cle.masked_voronoi_labeling(img_relevant_maxima, img)
    iterative_separation = voronoi_separation  
    dyn_separation = np.array(iterative_separation)    
            
    separated_mask = mask_separation(dyn_separation, img).astype("uint8") * 255  # Takes 101s for 42 images

    separated_mask2 = erase_border_neurons(separated_mask / 255).astype("uint8") * 255
    
    return separated_mask2


def F2Mask(img, size_limits = (80,600), sig = 2.5, *, name = '', ED_loops = 5):
    """
    Main function that has to be called to generate a mask from a fluorescence image.
    It will identify all neurons, and leave in the mask all those with areas given by size_limits.
    
    Boxes values inside of integers and finds where the background is situated based on the first derivative of that distribution.

    Loops from that tolerance starting point and stops when the number of neurons found falls below 80% of the initial value.

    PARAMETERS:
        
        img: The fluorescence image, ideally a ".tif" imported through OpenCV imread function, reading only layer 0.
                eg: img = cv.imread(path, 0)
        
        size_limits: While cleaning the mask, it gets rid of everything that doesn't have an area within the interval.

        sig: Value for the gaussian blur. Seems like the optimal value is 2.7 or similar.
        
        save: Indicates if the result should be saved by specifying a path.
        
        name: Indicates a name to show as the image being processed
        
    RETURNS:
        
        CMask: Cleaned Mask
        T: Optimal tolerance that has been found
        P-R: Optimal (Precision, Recall) pair corresponding to T
        neuron_count: the number of neurons identified
    """
    # make sure the image is given in a format from 0 to 255.
    if img.max() < 2: img = img * 255
    
    # Computes the starting point using the stabilization of the number of pixels in each box value in a histogram of the pixels of the image.
    X, R = hf.tol_dif(img)
    T_start = int(hf.convolve_derivative(X, R, DERIVATIVE= ["first"], show = False)[-1]) - 10
    assert(T_start > 0) 
    T_grid = hf.linspace(T_start, 255 - int(img.mean()) - 1, 1).astype(int)
    N = len(T_grid)

    neuron_count_max = 0
    
    for n, T in enumerate(T_grid):

        # Generates a mask based on ellipses around found maxima of brightness in img.
        img_relevant_maxima, mask_eroded = F2EMask(img, tolerance = T, box_half = p["box_half4_1"], 
                                                   size_interval = (p["size_interval4_2low"], p["size_interval4_2high"]), sigma = sig)

        # If there are no neurons left, continue
        if type(img_relevant_maxima) == type(None): continue

        # Generates the separated mask. Neurons are separated and border neurons erased.
        SMask = E2SMask(mask_eroded, img_relevant_maxima)

        # Erodes and dilates the neurons
        SMask_E = hf.erode_dilate(SMask, loops=ED_loops)
        
        if type(SMask_E) == type(None): continue

        # Cleans the mask
        CMask = hf.size_filter_v2(SMask_E, n_area_m = size_limits)

    
        neuron_count = hf.detect_maxima(CMask)[1]


        # Checks if this loop detected more neurons than the previous iterations. In this case we store it. 
        # This way we assume the best T is the one that maximizes the number of neurons detected.
        if neuron_count >= neuron_count_max:
            
            # This saves the initial count
            if n == 0: init_count = neuron_count
            
            neuron_count_max = neuron_count
            img_relevant_maxima_t = img_relevant_maxima.copy()
            mask_eroded_t = mask_eroded.copy()
            SMask_E_t = SMask_E.copy()
            CMask_t = CMask.copy()
            T_g = T
        
        if init_count * p["init_value_fraction2_2"] > neuron_count:
            print(f'\nFound breakpoint at iteration {n} / {N - 1} |  Best tolerance: {T_g}  |  Maximum tolerance reached: {T}') 
            break    
        
    return (CMask_t, neuron_count_max, T_g)
    

def mask_separation(voronoi_colour: np.array, mask: np.array):
    """
    voronoi_colour codes the instance classification of an image.
    mask is a semantic segmentation mask from the image, with no instance classification.
    
    Returns: a modified mask such that pixels that lie in the border of different instances in
    voronoi_colour are set to 0. This separates instances in the mask.
    """ 
    Indices = hf.extract_non_zero(voronoi_colour)
    for index in Indices:
        i,j = index
        positions = [-1, 0, 1]
        for row in positions:
            for column in positions:
                try:
                    if(voronoi_colour[i+row][j+column]!=0 and voronoi_colour[i+row][j+column]!=voronoi_colour[i][j]):
                        mask[i][j] = 0
                        voronoi_colour[i,j] = 0
                except IndexError:
                    continue
    return mask
 
# This code will be preserved here for the generation of the cropped images to put in the paper.    
if __name__ == "__main__":
    from _Preprocess import preprocess

    # This is called when the file is executed directly
    path = r"C:\Users\gerdy\Documentos\2 Neurociencia\Images\2024-04-11-ContrasteFase-Flourescencia\TincionNeuronas\F\1F.tif"
    img = cv.imread(path, 0)
    # crop = img[355:475, 177:308]
    img_t = preprocess(img)
    # crop_t = img_t[355:475, 177:308]

    a = F2Mask(img_t, (100, 550), 2.5)

    # save_folder = r"TestSave_2"  # This path can be relative to "path"
    # main(path, save_folder)
    
    pass
